# ansible n1 -m file -a "path=/home/ec2-user/n1-dir state=directory"…..
---
- name: install httpd server
  hosts: n1
  become: yes

  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: Start apache2
    service:
      name: apache2
      state: started

  - name: Enable apache2
    service:
      name: apache2
      enabled: yes
      
...