# ansible n1 -m file -a "path=/home/ec2-user/n1-dir state=directory"…..
---
- name: Install HTTPD server
  hosts: g1
  become: yes

  tasks:
  - name: install HTTPD
    yum:
      name: httpd
      state: present
    when: ansible_distributon == "Amazon"

  - name: Start Httpd
    service:
      name: httpd
      state: started
    when: ansible_distributon == "Amazon"
    
  - name: Enable httpd
    service:
      name: httpd
      enabled: yes
    when: ansible_distributon == "Amazon"

  - name: install Apache2
    apt:
      name: apache2
      state: present
    when: ansible_distributon == "Ubuntu"
    
  - name: Start apache2
    service:
      name: apache2
      state: started
    when: ansible_distributon == "Ubuntu"
    
  - name: Enable apache2
    service:
      name: apache2
      enabled: yes
    when: ansible_distributon == "Ubuntu"

...