---

- name: Variable Demo
  hosts: g1
  become: yes
  vars:
    ansible_username: Wbrymo

  tasks:
  - name: Update dynamic page
    template:
     src: dynamic.j2
     dest: /var/www/html/dynamic.html
...