# ansible n1 -m copy -a "content=Hello from Ansible! dest=/opt/devops/info.txt"   
---
- name: Ensure /opt/devops directory exists
  hosts: all
  become: yes
  tasks:
    - name: Create /opt/devops directory
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

    - name: Create info.txt file with content
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible!"
        
